### ISSUE TITLE
Incorrect/unwanted error message format

### ISSUE THREAD

**Issue by aliabe-creator** [g94angel/bible#1]
Current error handling in main.js line 132:

`.text(`${data.inputstring} is not in the Bible.`);`

produces unwanted error messages such as "Matthew is not in the Bible." or "Man is not in the Bible." It may be better to edit this error message to:

`.text(`Invalid verse reference(s) given. Try again.`);`

**Comment by g94angel** [comment]
I appreciate your suggestion. I refactored it 
.text(`${data.inputstring} is an invalid reference. Try again.`);
